CHORUS-TRE/workbench-operator

README.md, internal/controller/deployment.go, internal/controller/service.go, internal/controller/workbench_controller_test.go
The service is a bit confused but there is a workaround.
=> feat: proper initContainers usage

Makefile, charts/workbench-operator/.helmignore, charts/workbench-operator/Chart.yaml, charts/workbench-operator/templates/_helpers.tpl, charts/workbench-operator/templates/deployment.yaml, charts/workbench-operator/templates/leader-election-rbac.yaml, charts/workbench-operator/templates/manager-rbac.yaml, charts/workbench-operator/templates/serviceaccount.yaml, charts/workbench-operator/templates/workbench-crd.yaml, charts/workbench-operator/templates/workbench-editor-rbac.yaml, charts/workbench-operator/templates/workbench-viewer-rbac.yaml, charts/workbench-operator/values.yaml
This looks easier that turning our ApplicationSet to support kustomize (which is doable with ArgoCD).
=> feat(charts): Helm charts generated via helmify

charts/workbench-operator/templates/deployment.yaml, charts/workbench-operator/templates/workbench-crd.yaml, charts/workbench-operator/values.yaml
From 60f4bff
Signed-off-by: Yoan Blanc <yoan.blanc@chuv.ch>
=> fix(crds): missing ServiceAccount

api/v1alpha1/workbench_types.go, charts/workbench-operator/templates/workbench-crd.yaml, config/crd/bases/default.chorus-tre.ch_workbenches.yaml
Signed-off-by: Yoan Blanc <yoan.blanc@chuv.ch>
=> feat: validate some fields

cmd/main.go, internal/controller/config.go, internal/controller/deployment.go, internal/controller/job.go, internal/controller/workbench_controller_test.go
Will be needed once the applications are moved to another place in Harbor.
=> feat: allow configuration of applications repository

Makefile, charts/workbench-operator/templates/controller-manager-metrics-monitor.yaml, charts/workbench-operator/templates/deployment.yaml, charts/workbench-operator/values.yaml, config/default/chorus_patch.yaml, config/default/kustomization.yaml, config/manager/kustomization.yaml
6b4e897 feat: add Image and ImagePullSecrets (#24)
cdc95ca chore(deps): update dependency go to v1.23.2 (#26)
ded236d chore(deps): update golang docker tag to v1.23.2 (#27)
9339b80 feat: allow configuration of applications repository (#25)
de3ffe1 feat: validate some fields (#20)
c9ff208 fix(deps): update module github.com/onsi/gomega to v1.34.2 (#15)
18133ae chore: bump helmify and golangci-lint (#22)
9d9898d fix(crds): missing ServiceAccount (#19)
3cf8e52 chore(deps): update dependency go to v1.23.1 (#16)
=> prepare v0.0.1

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml
=> prepare v0.0.2

charts/workbench-operator/Chart.yaml, charts/workbench-operator/templates/manager-rbac.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, internal/controller/workbench_controller.go
Because we're using DeleteAllOf
=> fix: deletecollection is needed

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/default/chorus_patch.yaml
Since: https://github.com/CHORUS-TRE/images/pull/46
=> fix: xpra-server is in apps

charts/workbench-operator/Chart.yaml, ct.yaml, internal/controller/deployment.go, internal/controller/job.go
=> fix: xpra-server will be in apps too

internal/controller/job.go, internal/controller/workbench_controller_test.go
It will also clean things up after a day.
=> fix: one does not simply upgrade a job

charts/workbench-operator/Chart.yaml, charts/workbench-operator/templates/metrics-service.yaml, charts/workbench-operator/values.yaml, config/default/kustomization.yaml, config/manager/kustomization.yaml
=> ServiceMonitor needs an actual service

Makefile, charts/workbench-operator/Chart.yaml, charts/workbench-operator/templates/metrics-monitor.yaml, charts/workbench-operator/templates/workbench-crd.yaml, charts/workbench-operator/values.yaml, config/default/metrics_service.yaml, config/prometheus/monitor.yaml
=> fix: outdated CRDs in the Helm charts

api/v1alpha1/workbench_types.go, api/v1alpha1/zz_generated.deepcopy.go, charts/workbench-operator/Chart.yaml, config/crd/bases/default.chorus-tre.ch_workbenches.yaml, internal/controller/job.go
This will allow to be able to pass request and limit for each app + default values at the moment
=> feat : Update CRD for request + limit resources

charts/workbench-operator/values.yaml, cmd/main.go, config/manager/kustomization.yaml
Also use this PR to change registry.blabla to harbor.blabla  so that it's easier to test locally and up to date with everything
=> fix : Forgot to upgrade some version numbers that are not overloaded

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml, internal/controller/job.go
Update version number and forgot to update the one in config/manager/kustomization
=> fix : Update default resources (needed more for brainstorm)

config/default/chorus_patch.yaml
Replace unused registry (registry.build.chorus-tre.ch) with dev Harbor registry.
=> fix: Update default registry to dev Harbor.

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml
@sami-sweng @jnfrei you created a release without updating the tag in the code!!
this caused a deployment error on dev, please always check that your changed deploy successfully, thanks!
=> fix: tag was not updated

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml, internal/controller/job.go
bump to 0.3.11 (waiting for Sami [PR](https://github.com/CHORUS-TRE/workbench-operator/pull/69) before tagging for real)
=> fix : kiosk app check modified

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml, internal/controller/deployment.go, internal/controller/job.go, internal/controller/workbench_controller_test.go
=> feat : Mount data for juicefs poc

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml, internal/controller/workbench_controller.go
(and remove volume attributes that do not work it seems)
=> feat : Add juicefs label to pvc

api/v1alpha1/workbench_types.go, charts/workbench-operator/Chart.yaml, charts/workbench-operator/templates/workbench-crd.yaml, charts/workbench-operator/values.yaml, config/crd/bases/default.chorus-tre.ch_workbenches.yaml, config/manager/kustomization.yaml, config/samples/default_v1alpha1_workbench.yaml, internal/controller/job.go
This way we can have a username inside pods and deal with files
=> feat : Add username/uid to crd 

charts/workbench-operator/Chart.yaml, charts/workbench-operator/values.yaml, config/manager/kustomization.yaml, internal/controller/workbench_controller.go, internal/controller/workbench_controller_test.go
Now that we have the status of the xpra server, this way it will launch apps only when xpra is fully initialized and running
=> feat : Improve app launch
